# Generated by Django 4.2.15 on 2024-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app1', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
