# Generated by Django 4.2.15 on 2024-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousal_image',
            field=models.ImageField(default='photo', upload_to='product/'),
        ),
    ]
