# Generated by Django 4.2.15 on 2024-08-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
